//
//  File.swift
//  
//
//  Created by Maarten Engels on 18/09/2020.
//

import Foundation

let PLAYER_MAX_ACTION_POINTS = 15
let SIMULATION_NEXT_UPDATE_DELAY_MINUTES: Double = 1
let SHIP_BASE_WEIGHT = 3
let SHIP_ARMOR_UNIT_WEIGHT = 4
let SHIP_ARMAMENT_UNIT_WEIGHT = 5
let SHIP_BASE_SPEED = 1
//let SHIP_THRUST_UNIT_SPEED = 7
let SHIP_THRUST_UNIT_SPEED = 70
//let SHIP_WEIGHT_UNIT_SPEED = -2         // weight slows you down
let DISTANCE_BETWEEN_BASES: Double = 100
let NUMBER_OF_STINTS = 5
let PLAYER_SCAN_DISTANCE = 0.5
let PLAYER_ATTACK_DISTANCE = PLAYER_SCAN_DISTANCE
